### ISSUE TITLE
No Wifi

### ISSUE THREAD

**Issue by STE2k** [Jojo-A/MQTT-CAN-Gateway#3]
I m a newbie to all this stuff.. I flashed with Arduino IDE on the same board with the result:
. Variables and constants in RAM (global, static), used 35536 / 80192 bytes (44%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ DATA     1592     initialized variables
╠══ RODATA   3776     constants       
╚══ BSS      30168    zeroed variables
. Instruction RAM (IRAM_ATTR, ICACHE_RAM_ATTR), used 60447 / 65536 bytes (92%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ ICACHE   32768    reserved space for flash instruction cache
╚══ IRAM     27679    code in IRAM    
. Code in flash (default, ICACHE_FLASH_ATTR), used 369680 / 1048576 bytes (35%)
║   SEGMENT  BYTES    DESCRIPTION
╚══ IROM     369680   code in flash   

I think this is standard?  After flashing there is no WIFI  from ESP8266 and it blinks all the time. I don´t know where to put in my wifi ssid and password in this .ino file or how does it work?

**Comment by Jojo-A** [comment]
Hi,
although you closed this I still like to answer, maybe for further questions:
you don't need to enter your network credentials in the .ino file. There is the "WiFi Manager" which sets up a webserver in case that there are no known/valid WiFis. So you start it up, look for the hotspot that will be opened up by the device and log in. After that there should be a page where you can enter all necessary MQTT parameters as well as your WiFi credentials.Thats how most of the ESP8266 projects work.
If you are continuing with this please let me know if you have any troubles with that.

Cheers!
